# Generated by Django 4.2.7 on 2023-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=50)),
                ("task", models.ManyToManyField(to="task.taskmodel")),
            ],
        ),
    ]
