# Generated by Django 4.2.7 on 2023-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle", models.CharField(max_length=100)),
                ("taskDescreption", models.TextField()),
                ("isCompleted", models.BooleanField(default=False)),
                ("taskAssignDate", models.DateTimeField()),
            ],
        ),
    ]
